Update scripts to support OB Alpha release

diff --git a/modules/obam/templates/carbon-home/bin/wso2server.sh.erb b/modules/obam/templates/carbon-home/bin/wso2server.sh.erb
--- a/modules/obam/templates/carbon-home/bin/wso2server.sh.erb
+++ b/modules/obam/templates/carbon-home/bin/wso2server.sh.erb
@@ -34,57 +34,53 @@
 #ulimit -n 100000
 
 export JAVA_HOME="<%= @java_symlink %>"
-cygwin=false
-darwin=false
-os400=false
-mingw=false
-case "$(uname)" in
-CYGWIN*) cygwin=true ;;
-MINGW*) mingw=true ;;
-OS400*) os400=true ;;
-Darwin*)
-  darwin=true
-  if [ -z "$JAVA_VERSION" ]; then
-    JAVA_VERSION="CurrentJDK"
-  else
-    echo "Using Java version: $JAVA_VERSION"
-  fi
-  if [ -z "$JAVA_HOME" ]; then
-    JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
-  fi
-  ;;
+cygwin=false;
+darwin=false;
+os400=false;
+mingw=false;
+case "`uname`" in
+CYGWIN*) cygwin=true;;
+MINGW*) mingw=true;;
+OS400*) os400=true;;
+Darwin*) darwin=true
+        if [ -z "$JAVA_VERSION" ] ; then
+             JAVA_VERSION="CurrentJDK"
+           else
+             echo "Using Java version: $JAVA_VERSION"
+           fi
+           if [ -z "$JAVA_HOME" ] ; then
+             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
+           fi
+           ;;
 esac
 
 # resolve links - $0 may be a softlink
 PRG="$0"
 
 while [ -h "$PRG" ]; do
-  ls=$(ls -ld "$PRG")
-  link=$(expr "$ls" : '.*-> \(.*\)$')
-  if expr "$link" : '.*/.*' >/dev/null; then
+  ls=`ls -ld "$PRG"`
+  link=`expr "$ls" : '.*-> \(.*\)$'`
+  if expr "$link" : '.*/.*' > /dev/null; then
     PRG="$link"
   else
-    PRG=$(dirname "$PRG")/"$link"
+    PRG=`dirname "$PRG"`/"$link"
   fi
 done
 
 # Get standard environment variables
-PRGDIR=$(dirname "$PRG")
+PRGDIR=`dirname "$PRG"`
 
 # Only set CARBON_HOME if not already set
-[ -z "$CARBON_HOME" ] && CARBON_HOME=$(
-  cd "$PRGDIR/.."
-  pwd
-)
+[ -z "$CARBON_HOME" ] && CARBON_HOME=`cd "$PRGDIR/.." ; pwd`
 
 # Set AXIS2_HOME. Needed for One Click JAR Download
 AXIS2_HOME="$CARBON_HOME"
 
 # For Cygwin, ensure paths are in UNIX format before anything is touched
 if $cygwin; then
-  [ -n "$JAVA_HOME" ] && JAVA_HOME=$(cygpath --unix "$JAVA_HOME")
-  [ -n "$CARBON_HOME" ] && CARBON_HOME=$(cygpath --unix "$CARBON_HOME")
-  [ -n "$AXIS2_HOME" ] && CARBON_HOME=$(cygpath --unix "$CARBON_HOME")
+  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
+  [ -n "$CARBON_HOME" ] && CARBON_HOME=`cygpath --unix "$CARBON_HOME"`
+  [ -n "$AXIS2_HOME" ] && CARBON_HOME=`cygpath --unix "$CARBON_HOME"`
 fi
 
 # For OS400
@@ -101,28 +97,19 @@ if $os400; then
 fi
 
 # For Migwn, ensure paths are in UNIX format before anything is touched
-if $mingw; then
+if $mingw ; then
   [ -n "$CARBON_HOME" ] &&
-    CARBON_HOME="$( (
-      cd "$CARBON_HOME"
-      pwd
-    ))"
+    CARBON_HOME="`(cd "$CARBON_HOME"; pwd)`"
   [ -n "$JAVA_HOME" ] &&
-    JAVA_HOME="$( (
-      cd "$JAVA_HOME"
-      pwd
-    ))"
+    JAVA_HOME="`(cd "$JAVA_HOME"; pwd)`"
   [ -n "$AXIS2_HOME" ] &&
-    CARBON_HOME="$( (
-      cd "$CARBON_HOME"
-      pwd
-    ))"
+    CARBON_HOME="`(cd "$CARBON_HOME"; pwd)`"
   # TODO classpath?
 fi
 
-if [ -z "$JAVACMD" ]; then
-  if [ -n "$JAVA_HOME" ]; then
-    if [ -x "$JAVA_HOME/jre/sh/java" ]; then
+if [ -z "$JAVACMD" ] ; then
+  if [ -n "$JAVA_HOME"  ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
       # IBM's JDK on AIX uses strange locations for the executables
       JAVACMD="$JAVA_HOME/jre/sh/java"
     else
@@ -133,7 +120,7 @@ if [ -z "$JAVACMD" ]; then
   fi
 fi
 
-if [ ! -x "$JAVACMD" ]; then
+if [ ! -x "$JAVACMD" ] ; then
   echo "Error: JAVA_HOME is not defined correctly."
   echo " CARBON cannot execute $JAVACMD"
   exit 1
@@ -146,54 +133,55 @@ if [ -z "$JAVA_HOME" ]; then
 fi
 
 if [ -e "$CARBON_HOME/wso2carbon.pid" ]; then
-  PID=$(cat "$CARBON_HOME"/wso2carbon.pid)
+  PID=`cat "$CARBON_HOME"/wso2carbon.pid`
 fi
 
 # ----- Process the input command ----------------------------------------------
 args=""
-for c in $*; do
-  if [ "$c" = "--debug" ] || [ "$c" = "-debug" ] || [ "$c" = "debug" ]; then
-    CMD="--debug"
-    continue
-  elif [ "$CMD" = "--debug" ]; then
-    if [ -z "$PORT" ]; then
-      PORT=$c
-    fi
-  elif [ "$c" = "--stop" ] || [ "$c" = "-stop" ] || [ "$c" = "stop" ]; then
-    CMD="stop"
-  elif [ "$c" = "--start" ] || [ "$c" = "-start" ] || [ "$c" = "start" ]; then
-    CMD="start"
-  elif [ "$c" = "--version" ] || [ "$c" = "-version" ] || [ "$c" = "version" ]; then
-    CMD="version"
-  elif [ "$c" = "--restart" ] || [ "$c" = "-restart" ] || [ "$c" = "restart" ]; then
-    CMD="restart"
-  elif [ "$c" = "--test" ] || [ "$c" = "-test" ] || [ "$c" = "test" ]; then
-    CMD="test"
-  elif [ "$c" = "--optimize" ] || [ "$c" = "-optimize" ] || [ "$c" = "optimize" ]; then
-    for option in $*; do
-      if [ "$option" = "--skipConfigOptimization" ] || [ "$option" = "-skipConfigOptimization" ] ||
+for c in $*
+do
+    if [ "$c" = "--debug" ] || [ "$c" = "-debug" ] || [ "$c" = "debug" ]; then
+          CMD="--debug"
+          continue
+    elif [ "$CMD" = "--debug" ]; then
+          if [ -z "$PORT" ]; then
+                PORT=$c
+          fi
+    elif [ "$c" = "--stop" ] || [ "$c" = "-stop" ] || [ "$c" = "stop" ]; then
+          CMD="stop"
+    elif [ "$c" = "--start" ] || [ "$c" = "-start" ] || [ "$c" = "start" ]; then
+          CMD="start"
+    elif [ "$c" = "--version" ] || [ "$c" = "-version" ] || [ "$c" = "version" ]; then
+          CMD="version"
+    elif [ "$c" = "--restart" ] || [ "$c" = "-restart" ] || [ "$c" = "restart" ]; then
+          CMD="restart"
+    elif [ "$c" = "--test" ] || [ "$c" = "-test" ] || [ "$c" = "test" ]; then
+          CMD="test"
+    elif [ "$c" = "--optimize" ] || [ "$c" = "-optimize" ] || [ "$c" = "optimize" ]; then
+      for option in $*; do
+        if [ "$option" = "--skipConfigOptimization" ] || [ "$option" = "-skipConfigOptimization" ] ||
         [ "$option" = "skipConfigOptimization" ]; then
-        passedSkipConfigOptimizationOption=true
-        echo "Passed skipConfigOptimization Option: $passedSkipConfigOptimizationOption"
-      fi
-    done
-
-    for profile in $*; do
-      case "$profile" in
-      *Dprofile=*)
-        cd $(dirname "$0")
-        if [ "$passedSkipConfigOptimizationOption" = true ]; then
-          sh profileSetup.sh $profile --skipConfigOptimization
-        else
-          sh profileSetup.sh $profile
+          passedSkipConfigOptimizationOption=true
+          echo "Passed skipConfigOptimization Option: $passedSkipConfigOptimizationOption"
         fi
-        echo "Starting the server..."
-        ;;
-      esac
-    done
-  else
-    args="$args $c"
-  fi
+      done
+
+      for profile in $*; do
+        case "$profile" in
+          *Dprofile=*)
+            cd $(dirname "$0")
+            if [ "$passedSkipConfigOptimizationOption" = true ]; then
+              sh profileSetup.sh $profile --skipConfigOptimization
+            else
+              sh profileSetup.sh $profile
+            fi
+            echo "Starting the server..."
+            ;;
+        esac
+      done
+    else
+        args="$args $c"
+    fi
 done
 
 if [ "$CMD" = "--debug" ]; then
@@ -209,35 +197,36 @@ if [ "$CMD" = "--debug" ]; then
   echo "Please start the remote debugging client to continue..."
 elif [ "$CMD" = "start" ]; then
   if [ -e "$CARBON_HOME/wso2carbon.pid" ]; then
-    if ps -p $PID >/dev/null; then
+    if  ps -p $PID > /dev/null ; then
       echo "Process is already running"
       exit 0
     fi
   fi
   export CARBON_HOME="$CARBON_HOME"
-  # using nohup sh to avoid erros in solaris OS.TODO
-  nohup sh "$CARBON_HOME"/bin/wso2server.sh $args >/dev/null 2>&1 &
+# using nohup sh to avoid erros in solaris OS.TODO
+  nohup sh "$CARBON_HOME"/bin/wso2server.sh $args > /dev/null 2>&1 &
   exit 0
 elif [ "$CMD" = "stop" ]; then
   export CARBON_HOME="$CARBON_HOME"
-  kill -term $(cat "$CARBON_HOME"/wso2carbon.pid)
+  kill -term `cat "$CARBON_HOME"/wso2carbon.pid`
   exit 0
 elif [ "$CMD" = "restart" ]; then
   export CARBON_HOME="$CARBON_HOME"
-  kill -term $(cat "$CARBON_HOME"/wso2carbon.pid)
+  kill -term `cat "$CARBON_HOME"/wso2carbon.pid`
   process_status=0
-  pid=$(cat "$CARBON_HOME"/wso2carbon.pid)
-  while [ "$process_status" -eq "0" ]; do
-    sleep 1
-    ps -p$pid 2>&1 >/dev/null
-    process_status=$?
+  pid=`cat "$CARBON_HOME"/wso2carbon.pid`
+  while [ "$process_status" -eq "0" ]
+  do
+        sleep 1;
+        ps -p$pid 2>&1 > /dev/null
+        process_status=$?
   done
 
-  # using nohup sh to avoid erros in solaris OS.TODO
-  nohup sh "$CARBON_HOME"/bin/wso2server.sh $args >/dev/null 2>&1 &
+# using nohup sh to avoid erros in solaris OS.TODO
+  nohup sh "$CARBON_HOME"/bin/wso2server.sh $args > /dev/null 2>&1 &
   exit 0
 elif [ "$CMD" = "test" ]; then
-  JAVACMD="exec "$JAVACMD""
+    JAVACMD="exec "$JAVACMD""
 elif [ "$CMD" = "version" ]; then
   cat "$CARBON_HOME"/bin/version.txt
   cat "$CARBON_HOME"/bin/wso2carbon-version.txt
@@ -248,38 +237,47 @@ fi
 java_version=$("$JAVACMD" -version 2>&1 | awk -F '"' '/version/ {print $2}')
 java_version_formatted=$(echo "$java_version" | awk -F. '{printf("%02d%02d",$1,$2);}')
 if [ $java_version_formatted -lt 0107 ] || [ $java_version_formatted -gt 1100 ]; then
-  echo " Starting WSO2 Carbon (in unsupported JDK)"
-  echo " [ERROR] CARBON is supported only on JDK 1.7, 1.8, 9, 10 and 11"
+   echo " Starting WSO2 Carbon (in unsupported JDK)"
+   echo " [ERROR] CARBON is supported only on JDK 1.7, 1.8, 9, 10 and 11"
 fi
 
 CARBON_XBOOTCLASSPATH=""
-for f in "$CARBON_HOME"/lib/xboot/*.jar; do
-  if [ "$f" != "$CARBON_HOME/lib/xboot/*.jar" ]; then
-    CARBON_XBOOTCLASSPATH="$CARBON_XBOOTCLASSPATH":$f
-  fi
+for f in "$CARBON_HOME"/lib/xboot/*.jar
+do
+    if [ "$f" != "$CARBON_HOME/lib/xboot/*.jar" ];then
+        CARBON_XBOOTCLASSPATH="$CARBON_XBOOTCLASSPATH":$f
+    fi
 done
+
 
 CARBON_CLASSPATH=""
 if [ -e "$JAVA_HOME/lib/tools.jar" ]; then
-  CARBON_CLASSPATH="$JAVA_HOME/lib/tools.jar"
+    CARBON_CLASSPATH="$JAVA_HOME/lib/tools.jar"
 fi
-for f in "$CARBON_HOME"/bin/*.jar; do
-  if [ "$f" != "$CARBON_HOME/bin/*.jar" ]; then
-    CARBON_CLASSPATH="$CARBON_CLASSPATH":$f
-  fi
+for f in "$CARBON_HOME"/bin/*.jar
+do
+    if [ "$f" != "$CARBON_HOME/bin/*.jar" ];then
+        CARBON_CLASSPATH="$CARBON_CLASSPATH":$f
+    fi
 done
-for t in "$CARBON_HOME"/lib/*.jar; do
-  CARBON_CLASSPATH="$CARBON_CLASSPATH":$t
+for t in "$CARBON_HOME"/lib/*.jar
+do
+    CARBON_CLASSPATH="$CARBON_CLASSPATH":$t
 done
+for t in "$CARBON_HOME"/lib/endorsed/*.jar
+do
+    CARBON_CLASSPATH="$CARBON_CLASSPATH":$t
+done
+
 
 # For Cygwin, switch paths to Windows format before running java
 if $cygwin; then
-  JAVA_HOME=$(cygpath --absolute --windows "$JAVA_HOME")
-  CARBON_HOME=$(cygpath --absolute --windows "$CARBON_HOME")
-  AXIS2_HOME=$(cygpath --absolute --windows "$CARBON_HOME")
-  CLASSPATH=$(cygpath --path --windows "$CLASSPATH")
-  CARBON_CLASSPATH=$(cygpath --path --windows "$CARBON_CLASSPATH")
-  CARBON_XBOOTCLASSPATH=$(cygpath --path --windows "$CARBON_XBOOTCLASSPATH")
+  JAVA_HOME=`cygpath --absolute --windows "$JAVA_HOME"`
+  CARBON_HOME=`cygpath --absolute --windows "$CARBON_HOME"`
+  AXIS2_HOME=`cygpath --absolute --windows "$CARBON_HOME"`
+  CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
+  CARBON_CLASSPATH=`cygpath --path --windows "$CARBON_CLASSPATH"`
+  CARBON_XBOOTCLASSPATH=`cygpath --path --windows "$CARBON_XBOOTCLASSPATH"`
 fi
 
 # ----- Execute The Requested Command -----------------------------------------
@@ -291,18 +289,18 @@ cd "$CARBON_HOME"
 
 TMP_DIR="$CARBON_HOME"/tmp
 if [ -d "$TMP_DIR" ]; then
-  rm -rf "$TMP_DIR"/*
+rm -rf "$TMP_DIR"/*
 fi
 
 START_EXIT_STATUS=121
 status=$START_EXIT_STATUS
 
 if [ -z "$JVM_MEM_OPTS" ]; then
-  java_version=$("$JAVACMD" -version 2>&1 | awk -F '"' '/version/ {print $2}')
-  JVM_MEM_OPTS="-Xms<%= @jvmxms %> -Xmx<%= @jvmxmx %>"
-  if [ "$java_version" \< "1.8" ]; then
-    JVM_MEM_OPTS="$JVM_MEM_OPTS -XX:MaxPermSize=<%= @jvmxms %>"
-  fi
+   java_version=$("$JAVACMD" -version 2>&1 | awk -F '"' '/version/ {print $2}')
+   JVM_MEM_OPTS="-Xms<%= @jvmxms %> -Xmx<%= @jvmxmx %>"
+   if [ "$java_version" \< "1.8" ]; then
+      JVM_MEM_OPTS="$JVM_MEM_OPTS -XX:MaxPermSize=<%= @jvmxms %>"
+   fi
 fi
 echo "Using Java memory options: $JVM_MEM_OPTS"
 
@@ -311,12 +309,14 @@ echo "Using Java memory options: $JVM_MEM_OPTS"
 
 JAVA_VER_BASED_OPTS=""
 
+
 if [ $java_version_formatted -ge 1100 ]; then
-  JAVA_VER_BASED_OPTS="--add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED"
+    JAVA_VER_BASED_OPTS="--add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens java.rmi/sun.rmi.transport=ALL-UNNAMED"
 fi
 
-while [ "$status" = "$START_EXIT_STATUS" ]; do
-  $JAVACMD \
+while [ "$status" = "$START_EXIT_STATUS" ]
+do
+    $JAVACMD \
     -Xbootclasspath/a:"$CARBON_XBOOTCLASSPATH" \
     $JVM_MEM_OPTS \
     -XX:+HeapDumpOnOutOfMemoryError \
@@ -335,13 +335,13 @@ while [ "$status" = "$START_EXIT_STATUS" ]; do
     -Dcarbon.config.dir.path="$CARBON_HOME/repository/conf" \
     -Djava.util.logging.config.file="$CARBON_HOME/repository/conf/etc/logging-bridge.properties" \
     -Dcomponents.repo="$CARBON_HOME/repository/components/plugins" \
-    -Dconf.location="$CARBON_HOME/repository/conf" \
+    -Dconf.location="$CARBON_HOME/repository/conf"\
     -Dcom.atomikos.icatch.file="$CARBON_HOME/lib/transactions.properties" \
     -Dcom.atomikos.icatch.hide_init_file_path=true \
     -Dorg.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false \
     -Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true \
-    -Dcom.sun.jndi.ldap.connect.pool.authentication=simple \
-    -Dcom.sun.jndi.ldap.connect.pool.timeout=3000 \
+    -Dcom.sun.jndi.ldap.connect.pool.authentication=simple  \
+    -Dcom.sun.jndi.ldap.connect.pool.timeout=3000  \
     -Dorg.terracotta.quartz.skipUpdateCheck=true \
     -Djava.security.egd=file:/dev/./urandom \
     -Dfile.encoding=UTF8 \
@@ -352,6 +352,7 @@ while [ "$status" = "$START_EXIT_STATUS" ]; do
     -DworkerNode=false \
     -DenableCorrelationLogs=false \
     -Dcarbon.new.config.dir.path="$CARBON_HOME/repository/resources/conf" \
+    -Djavax.xml.xpath.XPathFactory:http://java.sun.com/jaxp/xpath/dom=net.sf.saxon.xpath.XPathFactoryImpl \
     org.wso2.carbon.bootstrap.Bootstrap $*
-  status=$?
+    status=$?
 done
